---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

params:
  MOVIE_FUN_URL:

inputs:
- name: movie-fun-source

run:
  path: movie-fun-source/ci/tasks/smoke-test.sh
